data:
  data_format: news
  his_size: 20 #Mind: 50
  npratio: 4
  title_size: 15 #Mind=30
info:
  metrics:
  - group_auc
  - mean_mrr
  - ndcg@5;10
  show_step: 100000
model:
  attention_hidden_dim: 200
  dropout: 0.2
  head_dim: 20
  head_num: 20
  model_type: nrms
  word_emb_dim: 300
train:
  batch_size: 32
  epochs: 10
  learning_rate: 0.0001
  loss: cross_entropy_loss
  optimizer: adam
  support_quick_scoring: true
